### ISSUE TITLE
Payment hängt mit TestNet3

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/PaymentService#35]
Beim Bezahlen mit TestNet3 hat sich den Process aufgehängt und ging es nicht weiter. Erst nachdem Manuel mit seinem Wallet ein neuer Auftrag bezahlte, ging es weiter. 
Ursache: unklar
Reproduzierbar: ?

**Comment by bockha** [comment]
![img-20170802-wa0000](https://user-images.githubusercontent.com/24431070/28865646-ed94f5d4-7770-11e7-98e9-d6fd9c24141d.jpg)
![img-20170802-wa0001](https://user-images.githubusercontent.com/24431070/28865645-ed8fd4dc-7770-11e7-968d-a8d9c2f021d7.jpg)

**Comment by gomarcel** [comment]
[Core_Payment.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a40db09354462000285b60/125516c66e82c728ace21e0d46cb9b8826bdb3a896e4ba4db01fbcd6395428792c07b7692ac7b670e7137f030c5e4ba9460d5612aef0892ba2b16f73835d19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc8b4ac8eb3d25e58e87482c53.txt)
[Mixer_PaymentService.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a40db09354462000285b60/125516c66e82c728ace21e0d46c59d822690bc998ef0b246aa49c3913b502e702c46ef696097ec22ba416f43554d4ba449590b16aff88c2ea1e33526d8550bedd56a0c77cf3c03b0aac04ee155e57dd205d0f4ae805ec2ee3724e28b8e49361d05188bf95d3db2d4.txt)

**Comment by gomarcel** [comment]
[mixer_docker_payment_mixer.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a40db09354462000285b60/125516c66e82c728ace21e0d46e59d822690bcad80eab446b662e095304b227d3d3bae226880f16af3006b1300051bff054a5556f9f1812af2e46f718f590cb8d83b0d7dc63d15abeb8116be13a632c91edbe2e3d7158abd7f37ed998c4e341f001888f75f3da59849cc59fe59ac.txt)
[tdmdocker_payment_core.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a40db09354462000285b60/125516c66e82c728ace21e0d46fc9097278d80a28afb8053a544fd91275218702616a6693cc7f33ab0487e021b4d44be44505745a8abda2aa3b33b25830a59e4d16d5b73953e18adaa9e0dfd50e474d412dcfce9c85ecafa3f23ed8a8a4f3f1607108cfe5f36a89b5985.txt)

**Comment by bockha** [comment]
The [transaction](https://testnet.blockexplorer.com/tx/9d47b563cc876fec848b926537774d603adb28de6f577ff705bde1210ba1708e) to [mstet8UzvKCvRF1GgarVwzbaHA5Y7oUKrd](https://testnet.blockexplorer.com/tx/9d47b563cc876fec848b926537774d603adb28de6f577ff705bde1210ba1708e) was successfuly mined into a block on 2nd of August. It seems that the smartphone wallet had a long delay before successfully broadcasting the transaction.

```
07:38:34.774 [qtp1901663135-15] INFO iuno.tdm.paymentservice.Bitcoin - 39b64f6a-3405-48ac-abfb-186be52f5f73 - bitcoin:mstet8UzvKCvRF1GgarVwzbaHA5Y7oUKrd?amount=0.002&label=PaymentService&message=all%20your%20coins%20belong%20to%20us
08:01:39.502 [bitcoinj user thread] INFO iuno.tdm.paymentservice.BitcoinInvoice - Received direct payment for invoice 39b64f6a-3405-48ac-abfb-186be52f5f73 to mstet8UzvKCvRF1GgarVwzbaHA5Y7oUKrd with 0.002 BTC
```
