### ISSUE TITLE
secure coupon redemption

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/PaymentService#4]
For redeeming coupons, an external [(web)service ](https://testnet.blockexplorer.com/)needs to be asked for all [UTXOs to a bitcoin address](https://testnet.blockexplorer.com/api/addr/mzrj4QmPhk98vc2yQw42uCsgwfBjVzPPLM/utxo). This service could reply with incorrect data, e.g. too few satoshis.

Ideally the payment service will use the external service only to look up the transaction ids of the UTXOs and then download the real transaction from the bitcoin network and check its inclusion in a block.

If this is not feasible, at least a trustworthy UTXO provider shall be used.

**Comment by hpbock** [comment]
maybe this is a helpful link https://github.com/visvirial/docker-insight

**Comment by goergch** [comment]
We now have a trustworthy UTXO provider with the block explorer integrated in the TDM d669fdd15d519c683c419bcc289acb44bb07551e

The Chance, that we get invalid TXs is now very low. And if we would get invalid TXs, the only thing that would happen is that the redemption doesn't work
