### ISSUE TITLE
Fix PaymentInterface Definition

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/PaymentService#5]
- [x] POST /invoices : All parameters should be passed within the body. You must not mix query and body parameters within a HTTP Post Call.

- [x] POST Method for Coupons: The Path should look like this: POST /invoices/{invoiceId}/coupons and all coupon parameters should be passed within the body.

Query-Parameters: For identifying resources.
Body-Parameters: For creating resources or setting new values.

**Comment by bockha** [comment]
@MBeuttler please review current draft again 
27e53d18e46eb8a8e46901de4ffd62edc10a5835

**Comment by MBeuttler** [comment]
One more point: When creating a resource via HTTP Post, the server should respond with a 201 created and the location header set.

```
responses:
        '201':
          description: operation succesful
          headers:
            location:
              description: The absolute path to the created resource
              type: string
```
